<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\DigitalProduct;
use Illuminate\Support\Str;

class DigitalProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'title' => 'Affiliate Marketing Landing Page Template',
                'description' => 'High-converting landing page template designed specifically for affiliate marketing campaigns with modern design and optimized conversion elements.',
                'slug' => Str::slug('Affiliate Marketing Landing Page Template'),
                'price' => 29.99,
                'category' => 'Templates',
                'subcategory' => 'Landing Pages',
                'image_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
                'badge' => 'Template',
                'is_sale' => false,
                'original_price' => null,
                'product_id' => '1249',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'title' => 'Bio Link For Your Social Media Profile',
                'description' => 'Create stunning bio link pages for your social media profiles with customizable templates and analytics tracking.',
                'slug' => Str::slug('Bio Link For Your Social Media Profile'),
                'price' => 49.99,
                'category' => 'Tools',
                'subcategory' => 'Social Media',
                'image_url' => 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
                'badge' => 'Tool',
                'is_sale' => false,
                'original_price' => null,
                'product_id' => '1141',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'title' => 'ChatGPT Pro - Advanced Language Model',
                'description' => 'Advanced language model for content creation and growth hacking with enhanced features and capabilities.',
                'slug' => Str::slug('ChatGPT Pro - Advanced Language Model'),
                'price' => 49.99,
                'category' => 'AI Tools',
                'subcategory' => 'Language Models',
                'image_url' => 'https://images.unsplash.com/photo-1677442136019-21780ecad995?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
                'badge' => 'AI Tool',
                'is_sale' => false,
                'original_price' => null,
                'product_id' => '1140',
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'title' => 'Enabling Growth: Entrepreneur\'s Guide to Digital Transformation',
                'description' => 'Comprehensive guide for entrepreneurs navigating digital transformation and business growth strategies.',
                'slug' => Str::slug('Enabling Growth: Entrepreneur\'s Guide to Digital Transformation'),
                'price' => 19.99,
                'category' => 'eBooks',
                'subcategory' => 'Business Guides',
                'image_url' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
                'badge' => 'eBook',
                'is_sale' => false,
                'original_price' => null,
                'product_id' => '1541',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'title' => 'How To Build Your Startup Future',
                'description' => 'Step-by-step guide to building a successful startup from idea to launch and beyond.',
                'slug' => Str::slug('How To Build Your Startup Future'),
                'price' => 19.99,
                'category' => 'Guides',
                'subcategory' => 'Startup Guides',
                'image_url' => 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
                'badge' => 'Guide',
                'is_sale' => false,
                'original_price' => null,
                'product_id' => '1918',
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'title' => 'Trend Loom Fashion Templates',
                'description' => 'Instagram post, Instagram story, social media Instagram post, Canva editable post templates for fashion brands.',
                'slug' => Str::slug('Trend Loom Fashion Templates'),
                'price' => 9.99,
                'category' => 'Templates',
                'subcategory' => 'Social Media',
                'image_url' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
                'badge' => 'Templates',
                'is_sale' => false,
                'original_price' => null,
                'product_id' => '759',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'title' => 'Unlocking the AI Business Frontier',
                'description' => 'Comprehensive guide to leveraging AI for business growth and competitive advantage.',
                'slug' => Str::slug('Unlocking the AI Business Frontier'),
                'price' => 9.99,
                'category' => 'AI Guides',
                'subcategory' => 'Business AI',
                'image_url' => 'https://images.unsplash.com/photo-1677442136019-21780ecad995?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
                'badge' => 'Sale',
                'is_sale' => true,
                'original_price' => 19.99,
                'product_id' => '1117',
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'title' => 'Urban Stitch Fashion Templates',
                'description' => 'Instagram post, Instagram story, social media Instagram post, Canva editable post templates for urban fashion.',
                'slug' => Str::slug('Urban Stitch Fashion Templates'),
                'price' => 9.99,
                'category' => 'Templates',
                'subcategory' => 'Social Media',
                'image_url' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
                'badge' => 'Templates',
                'is_sale' => false,
                'original_price' => null,
                'product_id' => '754',
                'is_active' => true,
                'sort_order' => 8,
            ],
            // Additional products for other categories
            [
                'title' => 'Premium SSL Certificate',
                'description' => 'Advanced SSL certificate with extended validation and wildcard support for complete domain security.',
                'slug' => Str::slug('Premium SSL Certificate'),
                'price' => 79.99,
                'category' => 'Hosting',
                'subcategory' => 'Security',
                'image_url' => 'https://images.unsplash.com/photo-1558494949-ef010cbcc31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
                'badge' => 'Security',
                'is_sale' => false,
                'original_price' => null,
                'product_id' => 'ssl001',
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'title' => 'Automated Cloud Backup Service',
                'description' => 'Daily automated backups with 30-day retention and instant restore capabilities for peace of mind.',
                'slug' => Str::slug('Automated Cloud Backup Service'),
                'price' => 29.99,
                'category' => 'Hosting',
                'subcategory' => 'Backup',
                'image_url' => 'https://images.unsplash.com/photo-1554469384-e58e1667caba?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
                'badge' => 'Backup',
                'is_sale' => false,
                'original_price' => null,
                'product_id' => 'backup001',
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'title' => 'Social Media Marketing Kit',
                'description' => 'Complete social media marketing kit with templates, content calendar, and strategy guides for 2025.',
                'slug' => Str::slug('Social Media Marketing Kit'),
                'price' => 39.99,
                'category' => 'Marketing',
                'subcategory' => 'Social Media',
                'image_url' => 'https://images.unsplash.com/photo-1611926653458-772ed24243f7?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
                'badge' => 'Marketing',
                'is_sale' => false,
                'original_price' => null,
                'product_id' => 'smm001',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'title' => 'Email Marketing Kit',
                'description' => 'Professional email marketing templates, automation sequences, and campaign strategies for higher conversions.',
                'slug' => Str::slug('Email Marketing Kit'),
                'price' => 34.99,
                'category' => 'Marketing',
                'subcategory' => 'Email',
                'image_url' => 'https://images.unsplash.com/photo-1554469384-e58e1667caba?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
                'badge' => 'Email',
                'is_sale' => false,
                'original_price' => null,
                'product_id' => 'emm001',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'title' => 'Business Pro WordPress Theme',
                'description' => 'Professional business WordPress theme with custom page builder, SEO optimization, and premium support.',
                'slug' => Str::slug('Business Pro WordPress Theme'),
                'price' => 59.99,
                'category' => 'WordPress',
                'subcategory' => 'Themes',
                'image_url' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
                'badge' => 'Theme',
                'is_sale' => false,
                'original_price' => null,
                'product_id' => 'wp001',
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'title' => 'SEO Optimizer Pro Plugin',
                'description' => 'Advanced SEO optimization plugin with real-time analysis, schema markup, and performance monitoring.',
                'slug' => Str::slug('SEO Optimizer Pro Plugin'),
                'price' => 44.99,
                'category' => 'WordPress',
                'subcategory' => 'Plugins',
                'image_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
                'badge' => 'Plugin',
                'is_sale' => false,
                'original_price' => null,
                'product_id' => 'wp002',
                'is_active' => true,
                'sort_order' => 14,
            ],
        ];

        foreach ($products as $product) {
            DigitalProduct::create($product);
        }
    }
}
